add quotes
addressing:
ERROR: Syntax Error while loading YAML script, /srv/web/infra/ansible/playbooks/hosts/fed-cloud09.cloud.fedoraproject.org.yml
Note: The error may actually appear before this position: line 11, column 19

   - /srv/web/infra/ansible/vars/fedora-cloud.yml
   - {{ private }}/files/openstack/passwords.yml
                  ^
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"