using syntax, which allows better formating
addressing:
ERROR: Syntax Error while loading YAML script, /srv/web/infra/ansible/playbooks/hosts/fed-cloud09.cloud.fedoraproject.org.yml
Note: The error may actually appear before this position: line 112, column 31

    glance_image:
      login_username: "admin" login_password: "{{ ADMIN_PASS }}" login_tenant_name: "admin"
                              ^
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"