apply change to mock epel5 config
mock in epel6 changed, and we need this change (takend from F20 config of mock)
to successfuly build el5 package

addressing:
DEBUG util.py:281:  error: cannot write to %sourcedir /usr/src/redhat/SOURCES